# The Windows build links the CRT statically, so the binary runs on a clean
# Windows install with no Visual C++ redistributable.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
